### ISSUE TITLE
Recurring Issue: Broken Links in Documentation - `https://miniature-adventure-4gle9ye.pages.github.io` Returning 404 Errors

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-storage#75]
Hello Team,

I wanted to bring to your attention an ongoing issue with the [Open Mobile Hub's Android OMH Storage](https://github.com/openmobilehub/android-omh-storage) repository. The documentation contains multiple links pointing to `https://miniature-adventure-4gle9ye.pages.github.io`, which are currently returning 404 errors.

This issue has been reported in the past in other repos, so it should have been caught this time, and it would be beneficial for us to resolve it to prevent any disruption for our developers and business development team. They rely on these pages to showcase the SDK to app developers effectively.

Here's a [search result](https://github.com/search?q=repo%3Aopenmobilehub%2Fandroid-omh-storage+https%3A%2F%2Fminiature-adventure-4gle9ye.pages.github.io&type=code) that highlights all instances where the incorrect domain is being referenced.

I understand that managing documentation can be challenging, and I appreciate the hard work everyone is doing. It would be great if we could update the links to ensure they reflect the correct URLs and maintain the reliability of our documentation.

Please let me know if there's anything I can do to assist in this process.

Thank you for your attention to this matter.

**Comment by Nataliagros** [comment]
Hi Diego, @adamTrz will look into that today

**Comment by dzuluaga** [comment]
Thank you, @adamTrz and @Nataliagros, for handling this. The changes look good at first glance. I’ll conduct a more thorough review next week.
