### ISSUE TITLE
Missing GIF Animations for Android OMH Storage

### ISSUE THREAD

**Issue by dzuluaga** [openmobilehub/android-omh-storage#76]
Hello team,

I noticed that the GIF animations for the Android OMH Storage are still missing from our repository. As I requested earlier, these animations are essential for both technical and non-technical audiences to grasp the concept and functionality of OMH Storage effectively.

**Importance:**

- **Visual Aid:** They provide a clear and quick understanding of OMH Storage features.
- **Audience Engagement:** Help engage and educate users across different learning preferences.

Please prioritize creating and adding these animations to the repository and update the documentation accordingly. It's important to address this promptly without needing reminders.

Thank you.

**Comment by adamTrz** [comment]
This should be fixed with #101 
@dzuluaga I'm closing this issue but please reopen if you feel that there's a need for additional documentation improvement 👍

**Comment by dzuluaga** [comment]
Thanks, @adamTrz. This looks good! The table displays correctly on the GitHub website, but there are some random characters appearing in the docs. Would it be possible for you to check this out? Thanks!

<img width="1041" alt="image" src="https://github.com/user-attachments/assets/079bb617-ff2e-4f8a-8a3c-8f185a87225e">
